# Generated by Django 5.2.1 on 2025-11-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('capacity', models.IntegerField(default=50)),
                ('current_traffic', models.IntegerField(default=0)),
                ('traffic_level', models.CharField(choices=[('low', 'Low - Green'), ('medium', 'Medium - Yellow'), ('high', 'High - Orange'), ('critical', 'Critical - Red')], default='low', max_length=10)),
                ('travel_time', models.FloatField(default=0)),
                ('from_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_roads', to='traffic.intersection')),
                ('to_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_roads', to='traffic.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.road')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
